version: '3'

services:

  database:
      image: postgres:15.2-alpine
      ports:
        - "5433:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=eshop

  eshop:
      image: sedov/eshop-backend:0.0.1-SNAPSHOT
      depends_on:
        - database
      ports:
        - 80:80
        - 443:443
      environment:
        - DATASOURCE_URL=jdbc:postgresql://database:5432/eshop
        - DATASOURCE_USER=postgres
        - DATASOURCE_PASSWORD=password